### ISSUE TITLE
[BUG] - SSR + Safari is flaky 

### ISSUE THREAD

**Issue by julrichter** [porsche-design-system/porsche-design-system#2335]
### Contact Details

#team-carsales-aircooled

### JS Framework

Next.js 12.2.4, Next.js 13.0.6

### Porsche Design System version

2.20.0

### What browsers are you seeing the problem on?

Safari

### Browser version

Version 16.3 (17614.4.6.11.4, 17614)

### Reproduction Example

https://finder.porsche.com/de/de-DE/search

### Steps to reproduce the behavior

1. Go to [finder](https://finder.porsche.com/de/de-DE/search)
2. Open Developer Tools and switch to the **Timelines** tab
4. Refresh page and inspect the rendered frames  
5. See that the first frames are rendered without the Porsche Design System components
![This is an image](https://i.ibb.co/SRSF0YV/Bildschirmfoto-2023-02-16-um-10-56-45.png)
![This is an image](https://i.ibb.co/XLMn9vD/Bildschirmfoto-2023-02-16-um-10-57-01.png)

### Expected behavior

Porsche Design System Components are rendered with the first frame and there is no flash of unstyled contend / layout shift

In Chrome (Version 109.0.5414.119) the issue can not be reproduced.

**Comment by affilnost** [comment]
The reason for it is that Safari & Firefox don't support Declarative Shadow DOM:

https://caniuse.com/declarative-shadow-dom

Pds components' styles are located for every component inside of Declarative Shadow DOM:
`<template shadowroot="open"><style>....</style>....</template>`

Therefore, without javascript enabled or before Ponyfill (js on client side) has been executed, the styles are not being applied (not working) in Safari and Firefox.

This effect is called "flash of unstyled content" (FOUC).

We have 2 options there:

1) Hide all pds components with css by default and show them only after Ponyfill has been executed. It will stop flaking for Safari & Firefox, but the Chrome's users will see the pds components later, only after Ponyfill has been executed. And for javascript disabled they will also be invisible.

2) Use inline styles or global styles for initial rendering. But it's bad for the performance and it then can't be called SSR anymore.


**Useful links:**

Declarative Shadow DOM:
https://developer.chrome.com/en/articles/declarative-shadow-dom/

SSR Next.js:
https://www.newline.co/@kchan/web-components-in-server-side-rendered-ssr-and-static-site-generated-ssg-in-nextjs-applications--6b2e93b2

**Comment by affilnost** [comment]
I also analyzed https://shop.porsche.com/de/de-DE - the same result there. Without javascript enabled PDS-Components' templates and styles are not applied.

The other (non-PDS) html-elements are styled correctly because they use inline-styles for them, instead of Declarative Shadow DOM.

Please see screenshots attached.

![Image](https://user-images.githubusercontent.com/2981884/223076077-ae828a48-5b75-40b4-8144-11a52786f572.jpg)
![Image](https://user-images.githubusercontent.com/2981884/223076078-61c54fd4-a385-43d8-a3d8-d306a0436016.jpg)
![Image](https://user-images.githubusercontent.com/2981884/223076079-e25b61b9-dd45-4983-8c4b-b65c87ae919b.jpg)



@stephanschroeter fyi

**Comment by affilnost** [comment]
As discussed in Daily, we don't have clean / quick solution for the moment, and Safari will support Declarative Shadow DOM starting from version 16.4, so nothing to do here.

**Comment by affilnost** [comment]
As discussed with Stephan and Bernd, I analyzed our DSRPonyfill and answered the following questions:

- Is it visible in Safari Debugger Timeline for https://shop.porsche.com/ and https://finder.porsche.com/?

Yes, you can see in the Timeline that there's a delay about 900 ms before pds components are displayed properly

- Is it visible in Timeline locally?

Yes, but only for overview page. There we have delay about 700 ms. So it depends on components' amount.

- DSRPonyfill - maybe we should go through "template" elements instead of going through the whole DOM

Currently we use "template-shadowroot" (https://github.com/webcomponents/template-shadowroot) script. There there are 2 implementations: "manual walk" (default one, we use it) and "queryselectorall". The second implementation does exactly it: "going through all template elements". I tried it out, but it still gave 700 ms delay. So no performance improvement.

- DSRPonyfill - maybe we should go through only "prefixed pds elements".

This improvement may be done (in order to exclude other non-pds-elements), but we will still have at least 700 ms delay (as locally for overview page) which still will be noticeable for the user. So we could win 200-300 milliseconds, but is it worth the time?

- Maybe customers can put the DSRPonyfill right after pds-elements / in the middle of dom / many times on the page

I tried it out locally: putting the DSRPonyfill in the middle of the page / after components which are visible on the page - it didn't bring any performance improvement. It looks like Safari first goes through the whole DOM till the end of the html, before applied Shadow DOM is being rendered. So it makes no sense to put DSRPonyfill anywhere else, only at the end of body.

**Comment by affilnost** [comment]
As discussed in Daily, Safari will support Declarative Shadow DOM starting from version 16.4, so we first wait till the new version, and the problem should be solved there.
