### ISSUE TITLE
Inject IntialStyles from partial in UXPin pages

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2427]
Scope
---
Currently the Design System requires the versioned initial styles partial to be used/injected into the head of an application to show all component styles appropriately. Therefore we have to integrate them in UX Pin editor and preview as well.

Notes  
---
- See React integration in docu: https://designsystem.porsche.com/v3/partials/initial-styles
- Partials are versioned as part of the components package

Acceptance criteria
---
- [ ] Initial styles are injected into UX Pin editor and previews with the same version as components

**Comment by michaelrambeau** [comment]
## First attempt

I prepared an experimental version of the Merge CLI that includes the styles from the partials in the library bundle

The strategy was:

- add a new `pageHeadContent` property in UXPin configuration that contains the mark-up to be injected later (`<style>...</style>`)
- Add a script in the library bundle to inject the styles at run time
- At run time, the script append those styles to the page `<head>` tag, in both Editor and Preview

The setup in `uxpin.config.js` looks like this:

```js
module.exports = {
  components: {
    pageHeadContent: require("@porsche-design-system/components-js/partials").getInitialStyles(),
    categories: [
      {
        name: 'Uncategorized',
        include: [
          'src/lib/components/Accordion/Accordion.tsx',
          'src/lib/components/Banner.tsx',
          'src/lib/components/Button.tsx',
```


However, injecting partials styles in the `<head>` of both Editor and Preview create CSS conflicts as the partials target global elements such as the `<body>`.

For example in the editor, the Porsche font shows up for dropdown menus:

![image](https://github.com/porsche-design-system/porsche-design-system/assets/5546996/5563ea44-c972-499c-8fd7-1a9d4e4e7945)

The result is even worse in Preview, the font breaks the layout:

![image](https://github.com/porsche-design-system/porsche-design-system/assets/5546996/f5937793-83ec-4173-b943-2f0593e43dcf)

So I don't think we should go further with this approach.

### Taking a step back

The real question is: what is the problem to solve?

@marcelbertram you mentioned a problem with `<Textfield type="search">`, could you give us an example?

What I can see is that the "magnifying glass" does not show up right away when you switch to `type = search`, you have to reload the window to get the icon.
It's not something related to partials.

When dropping on the canvas:

![image](https://github.com/porsche-design-system/porsche-design-system/assets/5546996/2a20c614-f341-4687-904b-24b9754848a8)

When reloading the browser:

![image](https://github.com/porsche-design-system/porsche-design-system/assets/5546996/0e8ef157-cdfa-43ed-b3e7-d7b5f072837e)

This problem is related with something I investigated previously: Porsche components are updated when changing the `type` property (the type property is not supposed to change dynamically): https://github.com/porsche-design-system/porsche-design-system/pull/2014

**Comment by michaelrambeau** [comment]
## Clarification of the issue to solve

What is happening is that in Chrome, the browser adds automatically a cross icon when there is an input value. It does not happen in Firefox.

> Some browsers show a cross icon that can be clicked on to remove the search term instantly if desired

Among the 4 KB of styles provided by the partials, there is some CSS code to disable this behavior.
Basically something like this:

```css
input::-webkit-search-cancel-button {
	display: none;
}
```

So we have to find a way to replicate this behavior without injecting all the styles, to avoid the global styles that conflict with UXPin styles

## Second attempt

To avoid style conflicts, instead of including the styles at the bottom of the `<head>` tag, they are included at the top (so that UXPin styles override them)

The latest release of Merge CLI (3.3.0) lets users inject any custom tag (`<style>` or `<script>`) in UXPin Editor and Preview.

Details in the PR: https://github.com/UXPin/uxpin-merge-tools/pull/401
