### ISSUE TITLE
[BUG] - Button-/Link-Pure "align-label=left" label is hidden on hover in Firefox

### ISSUE THREAD

**Issue by tatjana-gartner2** [porsche-design-system/porsche-design-system#2583]
### JS Framework

All frameworks

### Porsche Design System version

latest

### What browsers are you seeing the problem on?

Firefox

### Notes
- Reference: https://github.com/porsche-design-system/porsche-design-system/issues/2519

### Reproduction Example

https://designsystem.porsche.com/v3/components/button-pure/examples#alignment

### Steps to reproduce the behaviour

1. Go to https://designsystem.porsche.com/v3/components/button-pure/examples#alignment)
2. Hover p-button-pure align-label="left"
3. See error

### Expected behaviour

Label of Button Pure / Link Pure has to be visible on hover

**Comment by henrijoss** [comment]
Can't reproduce. Tested in FF 111 - 115 (latest).

**Comment by o-hook** [comment]
In the Storefront the issue can't be reproduced, everything works in Forefox.
But in Stackblitz and also on the temporary test page (index.html) the issue can be reproduced. The reason why the Storefront example works is somehow due to parent CSS selectors.

The following example does not work:

```
<body>
  <p-button-pure align-label="left">Some label</p-button-pure>
</body>
```

But this example works:
```
<body>
  <div style="overflow-x: auto; border-radius: 1px">
      <p-button-pure align-label="left">Some label</p-button-pure>
  </div>
</body>
```

Really strange though...
