### ISSUE TITLE
[BUG] - Model Signature not displayed inside of CSS-Grid in Safari when width is set to `auto`

### ISSUE THREAD

**Issue by michaelworm** [porsche-design-system/porsche-design-system#3210]
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1714999793694039

### JS Framework

Components-JS

### Porsche Design System version

latest

### On which device(s) you can see the bug?

Mac

### In which browsers you can see the bug?

Safari

### Browser version

17.4.1

### Reproduction Example

https://stackblitz.com/edit/wqiwuq-az7c9c?file=index.html

### Steps to reproduce the behavior

1. Go to Stackblitz in Safari
4. See error'

### Expected behavior

The Model Signature  should be visible.

It seems it has something todo with `--p-model-signature-width: auto` since setting a fixed with will resolve the issue

**Comment by o-hook** [comment]
This issue in Safari is caused by the internal components CSS property `max-width` which is set on the `:host` element. This somehow influences the rendering in Safari. Unfortunately, removing this CSS completely is not an option because it's needed to prevent exceeding the parent's height in some scenarios.

A user of `p-model-signature` component can fix this in Safari by overwriting the `max-width` on the `:host`element, e.g.:
```
<p-model-signature
      model="911"
      class="signature"
      safe-zone="false"
      style="max-width: inherit"
      ></p-model-signature>
```

But checking if the rendering is still correct in all Browsers and layout scenarios is mandatory.
