### ISSUE TITLE
Improve `componentsReady`

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#3394]
Scope
---
Teams aiming for maximum performance of their web application are looking for a way to detect as early as possible when PDS components have been bootstrapped. Therefor, we should evaluate if it's necessary to wait for `complete` readiness of document within `componentsReady` (`packages/components/src/components-ready.ts`) instead of e.g. `loading`. Alternatively, we could even make the `document.readyState` check configurable.

Notes  
---
<img width="975" alt="Screenshot 2024-07-10 at 14 57 16" src="https://github.com/porsche-design-system/porsche-design-system/assets/30120450/ca0be38f-2799-4ac6-8392-95a23dfce479">

Acceptance criteria
---
- [ ] `componentsReady` is resolving its promise as early as possible as soon as PDS components have been bootstrapped.

Subtasks
---
- [ ] Task

**Comment by kaiszybiak** [comment]
In PR #3460 we made the [`readyState`](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) of `componentsReady` configurable and added minor speed improvements by e.g. removing recursion and using `regex.test()` instead of `reges.exec()`. However it seems that the `componentOnReady` function is first available if `readyState = complete`:

<img width="574" alt="Bildschirmfoto 2024-08-16 um 13 44 53" src="https://github.com/user-attachments/assets/6e5689ec-8041-4120-b884-33885b879677">

Expecting the `readyState` to be anything other than `complete` will result in a `TypeError: window.porscheDesignSystem.componentsReady is not a function`

The [`appload`](https://stenciljs.com/docs/api#the-appload-event) event is triggered after `readyState = complete`.  So listening to `appload` instead wouldn't be a performance improvement.

As said [`readyState = interactive` ](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#interactive) is to early:

> The document has finished loading and the document has been parsed but sub-resources such as scripts, images, stylesheets and frames are still loading. The state indicates that the [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) event is about to fire.

But if we listen to the `DOMContentLoaded` event, the component `componentsReady()` is defined.

We can test the performance gain as follows: 

```HTML
    <script>
      const startTime = performance.now();

      document.addEventListener('readystatechange', async (event) => {
        const endTime = performance.now();
        const timeTaken = endTime - startTime;
        console.log('[Event:readystatechange]', event.srcElement.readyState);
        const res = await window.porscheDesignSystem.componentsReady();
        console.log('[Event:readystatechange]', res);
        console.log(`[Event:readystatechange:time] ${timeTaken.toFixed(2)} ms`);
      });

      document.addEventListener('DOMContentLoaded', async (event) => {
        const endTime = performance.now();
        const timeTaken = endTime - startTime;
        const res = await window.porscheDesignSystem.componentsReady();
        console.log('[Event:DOMContentLoaded]', event.srcElement.readyState, res);
        console.log(`[Event:DOMContentLoaded:time] ${timeTaken.toFixed(2)} ms`);
      });

      window.addEventListener('appload', async (event) => {
        const endTime = performance.now();
        const timeTaken = endTime - startTime;
        const res = await window.porscheDesignSystem.componentsReady();
        console.log('[Event:appload]', event.detail, res);
        console.log(`[Event:appload:time] ${timeTaken.toFixed(2)} ms`);
      });
    </script>
```

| Run  | DOMContentLoaded (ms) | readystatechange:complete (ms) | Difference (ms) |
|----|-----------------------:|------------------------------:|----------------:|
| 1  |                  20.30 |                         25.00 |            4.70 |
| 2  |                  20.40 |                         25.00 |            4.60 |
| 3  |                  25.10 |                         29.60 |            4.50 |
| 4  |                  28.20 |                         33.00 |            4.80 |
| 5  |                  27.90 |                         34.00 |            6.10 |
| 6  |                  22.20 |                         26.90 |            4.70 |
| 7  |                  23.00 |                         29.00 |            6.00 |
| 8  |                  21.70 |                         26.20 |            4.50 |
| 9  |                  22.30 |                         27.00 |            4.70 |
| 10 |                  23.20 |                         29.60 |            6.40 |


| Event                         | Average Time (ms) |
|-------------------------------|------------------:|
| `DOMContentLoaded`             |            23.43  |
| `readystatechange:complete`    |            28.53  |
| **Average Difference**         |             5.10  |

If we switch from listening to the `readystatechange` event with `readyState = complete` to `DOMContentLoaded` we could potentially save around 5.10 milliseconds. Not sure I this would justify a change 🤔
