### ISSUE TITLE
[BUG] - Carousel has exceedingly large whitespace on bigger resolutions and limited container size

### ISSUE THREAD

**Issue by Rouby** [porsche-design-system/porsche-design-system#3413]
### Contact Details

jonathan.burke@codecentric.de

### JS Framework

React

### Porsche Design System version

3.13.0

### Reproduction Example

https://react-wq4xsn-wnrf95.stackblitz.io

### Steps to reproduce the behavior

1. Go to https://react-wq4xsn-wnrf95.stackblitz.io
2. Use devtools to simulate different viewport sizes
3. See that viewport sizes above 1000px create visual problems

<img width="600" alt="image" src="https://github.com/user-attachments/assets/d069152e-5cbe-426f-bd6f-9697a6555fe6">

### Expected behavior

The carousel should not scale its whitespace according to viewport width if it is limited by its container to a smaller size.

**Comment by o-hook** [comment]
Hi @Rouby, thanks for reporting! 
Unfortunately the Stackblitz example is not a supported use case and therefor causes the described issue. In the example you set a `max-width: 1000px` on a wrapping container. But as described in the PDS docs, the `carousel` can only be used on "**full viewport width**": https://designsystem.porsche.com/v3/components/carousel/examples

**Comment by Rouby** [comment]
Btw The same issue is also present in the documentation on the design system website.

**Comment by o-hook** [comment]
Hi @Rouby,
yes, we know that the example implementation in our PDS Storefront is basically not correct. But this is due to our Storefront layout. Therefor we have added the "maximize" view to have a slightly better simulation of a real world use case.

Long story short: Currently, the `Carousel` component can only be used inside either `basic` or `extended` PDS Grid. If you put the component in a custom container with a custom width, it will probably not work.

**Comment by Rouby** [comment]
Thanks for the clarification 👍
