### ISSUE TITLE
Segmented Control in Scroller

### ISSUE THREAD

**Issue by finn-quoos** [porsche-design-system/porsche-design-system#3653]
### Portfolio

Customer

### ART and Team

My Porsche ART

### Contact Details

finn.quoos@porsche.de

### Problem

We want to use the segmented control component to filter content on a page. To ensure accessibility on mobile viewports, we intend to nest the segmented control in a scroller.

Example can be found [here](https://www.figma.com/design/1h3MNSvxxHKWI5YMbN405R/Messages?node-id=2160-78&t=W01Dgycs8Fv3gbF8-1)

### Solution ideas and examples

Enable segmented control component to be placed in scroller.

### Business priority

High

**Comment by o-hook** [comment]
Hi @finn-quoos,
thanks for the input! We should discuss (also from a usability perspective), if placing the segmented control inside a `scroller´ component is the best approach. Because if we support this behavior, it means, that all controls are placed in one row and are scrollable (sure). But this leads to eventually hidden selected controls which might be somehow confusing to the user. The user must somehow remember which filters have been set or check if there are some filters that have been preset (because they might be in the hidden area).

@neuncreative and @muellernaumann: what do you think?

Otherwise we should think about this behavior in the upcoming `Filter Chips` component: #3650
